### ISSUE TITLE
Parse patches on a per-language basis

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#11]
Short term goals:
+ tokenize changesets (for each lang.)
+ remove stop words (for each lang.)

and insert into Solr

**Comment by damevski** [comment]
We could add a few regular expressions specific to each language here. For instance, removing variable names if they are on the left side of an '=' sign in most imperative languages. It would help control the noise.

**Comment by seefo** [comment]
Finished as of https://github.com/vcu-swim-lab/KnowHows/commit/f1aba4ab51e5a75690e4ea6205ff85d8c5c13130

**Comment by seefo** [comment]
Updated issue title to be more accurate.

**Comment by damevski** [comment]
Use SrcML for now
