### ISSUE TITLE
Allow natural language queries

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#13]
Current plan is to have:
```
/knowhows BufferedOutputWriter
@alex, @ben, @robbie
```
However, if we use StackOverflow as planned in #12, we could cleverly allow for NL queries like
```
/knowhows writing a file in Java
@alex, @ben, @robbie
```

**Comment by broem** [comment]
Query-handling should now work with natural language queries. Upgrades have been made to how diffs are indexed and queried upon. Now when a diff is inserted we tokenize, remove common english stopwords, create an index of edge-wise ngrams, and stem. When querying we remove query stop words, stem, trim, etc. 
Right now assumption is "in _language_" should be provided to further filter for requests.
