### ISSUE TITLE
revise search command

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#17]
Revise search command to ```/knowhows on X in LanguageY``` from `/knowhows search`. do we want two separate commands e.g. `/knowhows to` for ambiguous queries and `/knowhows on` for exact queries, or is that too hard to remember

**Comment by AlexAplin** [comment]
I think one unified query would work, like `/knowhows to FileWriter in Java`  and `/knowhows to Write to a file in Java`. If the query is one word, use the exact query.

**Comment by damevski** [comment]
@AlexAplin is correct. Let's stick with `/knowhows to` for now. We can talk about ambiguous queries later, maybe.
