### ISSUE TITLE
Remove lang-specific stop words from srcml output

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/KnowHows#29]

**Comment by AlexAplin** [comment]
@damevski Pass along lists for these when you can. Plugging them in should be pretty simple.

**Comment by damevski** [comment]
sent it on slack

**Comment by AlexAplin** [comment]
Now filtering for Java.

**Comment by AlexAplin** [comment]
Now filtering reserved words for C, C++, and C#.

**Comment by AlexAplin** [comment]
Now filtering reserved words for C, C++, and C#.
